label variable hrhhid "Household identifier (part 1)"
label variable hrmonth "Month of interview"
label variable hryear4 "Year of interview"
label variable hurespli "Line number of the current respondent"
label variable hufinal "Final outcome code"
label variable huspnish "Is spanish the only language spoken by all members of this household who are 15 years of age or older?"
label variable hetenure "Are your living quarters..."
label variable hehousut "Type of housing unit"
label variable hetelhhd "Is there a telephone in this house/apartment? "
label variable hetelavl "Is there a telephone elsewhere on which people in this household can be contacted?"
label variable hephoneo "Is a telephone interview acceptable?"
label variable hefaminc "Family income"
label variable hutypea "Type A non-interview reason"
label variable hutypb "Type B non-interview reason"
label variable hutypc "Type C non-interview reason"
label variable hwhhwgt "Household weight"
label variable hrintsta "Interview status"
label variable hrnumhou "Total number of persons living in the household (household members)"
label variable hrhtype "Household type"
label variable hrmis "Month-in-sample"
label variable huinttyp "Type of interview"
label variable huprscnt "Number of actual and attempted personal contacts"
label variable hrlonglk "Longitudinal link indicator"
label variable hrhhid2 "Household identifier (part 2)"
label variable hwhhwtln "Line Number (PULINENO) of the person whose PWSSWGT was donated as HWHHWGT for the household"
label variable hubus "Does anyone in this household have a business or a farm?"
label variable hubusl1 "Enter line number for hubus = 1"
label variable hubusl2 "Enter line number for hubus = 1"
label variable hubusl3 "Enter line number for hubus = 1"
label variable hubusl4 "Enter line number for hubus = 1"
label variable gereg "Region"
label variable gediv "Division"
label variable gestfips "Federal information processing standards (FIPS) state code"
label variable gtcbsa "Specific Metropolitan CBSA FIPS code"
label variable gtco "FIPS county code"
label variable gtcbsast "Principal city/balance status"
label variable gtmetsta "Metropolitan status"
label variable gtindvpc "Individual principal city"
label variable gtcbsasz "Metropolitan area (CBSA) size"
label variable gtcsa "Consolidated statistical area (CSA) FIPS code"
label variable perrp "Relationship to reference person"
label variable peparent "Line number of parent"
label variable prtage "Persons age"
label variable prtfage "Top code flag for age"
label variable pemaritl "Marital status"
label variable pespouse "Line number of spouse"
label variable pesex "Sex"
label variable peafever "Did you ever serve on active duty in the U.S. armed forces?"
label variable peafnow "Are you now in the armed forces?"
label variable peeduca "Highest level of school completed or degree received"
label variable ptdtrace "Race"
label variable prdthsp "Detailed Hispanic origin group (Revised January 2014)"
label variable puchinhh "Change in household composition"
label variable pulineno "Person's line number"
label variable prfamnum "Family number recode"
label variable prfamrel "Family relationship recode"
label variable prfamtyp "Family type recode"
label variable pehspnon "Hispanic or non-Hispanic"
label variable prmarsta "Marital status based on armed forces participation"
label variable prpertyp "Type of person record recode"
label variable penatvty "Country of birth"
label variable pemntvty "Mother's country of birth"
label variable pefntvty "Father's country of birth"
label variable prcitshp "Citizenship status"
label variable prcitflg "Citizenship allocation flag"
label variable prinusyr "Immigrant' s year of entry"
label variable puslfprx "Labor force information collected by self or proxy response"
label variable pemlr "Monthly labor force recode"
label variable puwk "Last week, did you do any work for (either) pay (or profit)?"
label variable pubus1 "Last week, did you do any unpaid work in the family business or farm?"
label variable pubus2ot "Do you receive any payments or profits from the business?"
label variable pubusck1 "Check item 1 filter for questions on unpaid work"
label variable pubusck2 "Check item 2 skips owners of family busines who did not work last week"
label variable pubusck3 "Check item 3"
label variable pubusck4 "Check item 4"
label variable puretot "Retirement status (last month you were reported to be retired, are you still retired this month?)"
label variable pudis "Disability status (last month you were reported to have a disability.) Does your disability continue to prevent you from doing any kind of work for the next 6 months?"
label variable peret1 "Do you currently want a job, either full or part-time?"
label variable pudis1 "Does your disability prevent you from accepting any kind of work during the next six months?"
label variable pudis2 "Do you have a disability that prevents you from accepting any kind of work during the next six months?"
label variable puabsot "Last week did you have a job either full or part-time?"
label variable pulay "Last week, were you on layoff from a job?"
label variable peabsrsn "What is the main reason you were absent from work last week?"
label variable peabspdo "Are you being paid by your employer for any of the time off last week?"
label variable pemjot "Do you have more than one job?"
label variable pemjnum "Altogether, how many jobs did you have?"
label variable pehrusl1 "How many hours per week do you usually work at your main job?"
label variable pehrusl2 "How many hours per week do you usually work at your other (job/jobs)?"
label variable pehrftpt "Do you usually work 35 hours or more per week?"
label variable pehruslt "Sum of HRUSL1 and HRUSL2."
label variable pehrwant "Do you want to work a full-time work week of 35 hours or more per week?"
label variable pehrrsn1 "What is your main reason for working part-time?"
label variable pehrrsn2 "What is the main reason you do not want to work full-time?"
label variable pehrrsn3 "What is the main reason you worked less than 35 hours last week?"
label variable puhroff1 "Last week, did you lose or take off any hours from your job, for any reason such as illness, slack work, vacation, or holiday?"
label variable puhroff2 "How many hours did you take off?"
label variable puhrot1 "Last week, did you work any overtime or extra hours (at your main job) that you do not usually work?"
label variable puhrot2 "How many additional hours did you work?"
label variable pehract1 "Last week, how many hours did you actually work at your job?"
label variable pehract2 "Last week, how many hours did you actually work at your other (job/jobs)"
label variable pehractt "Sum of PEHRACT1 and PEHRACT2"
label variable pehravl "Last week, could you have worked full-time if the hours had been available?"
label variable puhrck1 "Check item 1"
label variable puhrck2 "Check item 2 skips persons responding yes to HRFTPT out of PT series"
label variable puhrck3 "Check item 3"
label variable puhrck4 "Check item 4"
label variable puhrck5 "Check item 5"
label variable puhrck6 "Check item 6"
label variable puhrck7 "Check item 7"
label variable puhrck12 "Check item 12"
label variable pulaydt "Has your employer given you a date to return to work?"
label variable pulay6m "Have you been given any indication that you will be recalled to work within the next 6 months?"
label variable pelayavl "Could you have returned to work last week if you had been recalled?"
label variable pulayavr "Why is that?"
label variable pelaylk "Even though you are to be called back to work, have you been looking for work during the last 4 weeks."
label variable pelaydur "Duration of layoff"
label variable pelayfto "FT/PT status of job from which sample person was on layoff from"
label variable pulayck1 "Check item 1"
label variable pulayck2 "Check item 2 screen for dependent layoff"
label variable pulayck3 "Check item 3 filter for dependent I & O"
label variable pulk "Have you been doing anything to find work during the last 4 weeks?"
label variable pelkm1 "What are all of the things you have done to find work during the last 4 weeks? (first method)"
label variable pulkm2 "Anything else? (second method)"
label variable pulkm3 "Anything else? (third method)"
label variable pulkm4 "Anything else? (fourth method)"
label variable pulkm5 "Anything else? (fifth method)"
label variable pulkm6 "Anything else? (sixth method)"
label variable pulkdk1 "You said you have been trying to find work. How did you go about looking? (first method)"
label variable pulkdk2 "Anything else? (second method)"
label variable pulkdk3 "Anything else? (third method)"
label variable pulkdk4 "Anything else? (fourth method)"
label variable pulkdk5 "Anything else? (fifth method)"
label variable pulkdk6 "Anything else? (sixth method)"
label variable pulkps1 "Can you tell me more about what you did to search for work? (first method)"
label variable pulkps2 "Anything else? (second method)"
label variable pulkps3 "Anything else? (third method)"
label variable pulkps4 "Anything else? (fourth method)"
label variable pulkps5 "Anything else? (fifth method)"
label variable pulkps6 "Anything else? (sixth method)"
label variable pelkavl "Last week, could you have started a job if one had been offered?"
label variable pulkavr "Why is that?"
label variable pelkll1o "Before you started looking for work, what were you doing: working, going to school, or something else?"
label variable pelkll2o "Did you lose or quit that job, or was it a temporary job that ended?"
label variable pelklwo "When last worked"
label variable pelkdur "Duration of job seeking"
label variable pelkfto "FT/PT status of jobseeker"
label variable pedwwnto "Do you currently want a job, either full or part time?"
label variable pedwrsn "What is the main reason you were not looking for work during the last 4 weeks?"
label variable pedwlko "Did you look for work at any time in the last 12 months"
label variable pedwwk "Did you actually work at a job or business during the last 12 months?"
label variable pedw4wk "Did you do any of this work during the last 4 weeks?"
label variable pedwlkwk "Since you left that job or business have you looked for work?"
label variable pedwavl "Last week, could you have started a job if one had been offered?"
label variable pedwavr "Why is that?"
label variable pudwck1 "Screen for discouraged workers"
label variable pudwck2 "Screen for disabled"
label variable pudwck3 "Filter for retired"
label variable pudwck4 "Filter for passive job seekers"
label variable pudwck5 "Filter for passive job seekers"
label variable pejhwko "Have you worked at a job or business at any time during the past 12 months?"
label variable pujhdp1o "Did you do any of this work in the last 4 weeks?"
label variable pejhrsn "What is the main reason you left your last job?"
label variable pejhwant "Do you intend to look for work during the next 12 months?"
label variable pujhck1 "Filter for outgoing rotations"
label variable pujhck2 "Filter for persons going through the I and O series"
label variable prabsrea "Reason not at work and pay status"
label variable prcivlf "Civilian labor force"
label variable prdisc "Discouraged worker recode"
label variable premphrs "Reason not at work or hours at work"
label variable prempnot "MLR - employed, unemployed, or NILF"
label variable prexplf "Experienced labor force employment"
label variable prftlf "Full time labor force"
label variable prhrusl "Usual hours worked weekly"
label variable prjobsea "Job search recode"
label variable prpthrs "At work 1-34 by hours at work"
label variable prptrea "Detailed reason for part-time"
label variable prunedur "Duration of unemployment for layoff and looking records"
label variable pruntype "Reason for unemployment"
label variable prwksch "Labor force by time worked or lost"
label variable prwkstat "Full/part-time work status"
label variable prwntjob "NILF recode - want a job or other NILF"
label variable pujhck3 "Job history check item"
label variable pujhck4 "Screen for dependent NILF"
label variable pujhck5 "Screen for dependent NILF"
label variable puiodp1 "Last month, it was reported that you worked for (employer's name). Do still work for (employer's name) (at your main job)?"
label variable puiodp2 "Have the usual activities and duties of your job changed since last month?"
label variable puiodp3 "Last month you were reported as (a/an) (occupation) and your usual activities were (description). Is this an accurate description of your current job?"
label variable peio1cow "Individual class of worker code on first job"
label variable puio1mfg "Is this business or organization mainly manufacturing, retail trade, wholesale trade, or something else?"
label variable peio2cow "Individual class of worker on second job."
label variable puio2mfg "Is this business or organization mainly manufacturing, retail trade, wholesale trade, or something else?"
label variable puiock1 "I & O check item 1 screen for dependent I and O"
label variable puiock2 "I & O check item 2 screen for previous months I and O cases"
label variable puiock3 "I & o check item 3"
label variable prioelg "Industry and occupation eligibility flag"
label variable pragna "Agriculture/ non-agriculture industry"
label variable prcow1 "Class of worker recode - job 1"
label variable prcow2 "Class of worker recode - job 2"
label variable prcowpg "COW - private or government"
label variable prdtcow1 "Detailed class of worker recode - job 1"
label variable prdtcow2 "Detailed class of worker recode - job 2"
label variable prdtind1 "Detailed industry recode - job 1"
label variable prdtind2 "Detailed industry recode - job 2"
label variable prdtocc1 "Detailed occupation recode - job 1"
label variable prdtocc2 "Detailed occupation recode - job 2"
label variable premp "Employed persons (non-farm & non-private hhld) recode"
label variable prmjind1 "Major industry recode - job 1"
label variable prmjind2 "Major industry recode - job 2"
label variable prmjocc1 "Major occupation recode - job 1"
label variable prmjocc2 "Major occupation recode - job 2"
label variable prmjocgr "Major occupation categories"
label variable prnagpws "Non-agriculture, private wage and salary workers recode"
label variable prnagws "Non-agriculture wage and salary workers recode"
label variable prsjmj "Single/multiple jobholder"
label variable prerelg "Earnings eligibility flag"
label variable peernuot "Do you usually receive overtime pay, tips, or commissions at your job?"
label variable peernper "Periodicity"
label variable peernrt "(Even though you told me it is easier to report your earnings (periodicity); Are you paid at an hourly rate on your (main/this) job?"
label variable peernhry "Hourly/nonhourly status"
label variable puernh1c "What is your hourly rate of pay on this job, excluding overtime pay, tips or commission?"
label variable peernh2 "(Excluding overtime pay, tips and commissions) what is your hourly rate of pay on your (main/this) job?"
label variable peernh1o "Out variable for hourly rate of pay"
label variable prernhly "Recode for hourly rate"
label variable pthr "Hourly pay - top code"
label variable peernhro "Usual hours"
label variable prernwa "Weekly earnings recode"
label variable ptwk "Weekly earnings - top code"
label variable peern "Calculated weekly overtime amount"
label variable puern2 "Calculated weekly overtime amount"
label variable ptot "Weekly overtime amount - top code"
label variable peernwkp "How many weeks a year do you get paid for?"
label variable peernlab "On this job, are you a member of a labor union or of an employee association similar to a union?"
label variable peerncov "On this job are you covered by a union or employee association contract?"
label variable penlfjh "When did you last work at a job or business?"
label variable penlfret "Are you retired from a job or business?"
label variable penlfact "What best describes your situation at this time? For example, are you disabled, ill, in school, taking care of house or family, or something else?"
label variable punlfck1 "Not in labor force check item - 1"
label variable punlfck2 "Not in labor force check item - 2"
label variable peschenr "Last week, were you enrolled in a high school, college, or university?"
label variable peschft "Are you enrolled in school as a full-time or part-time student?"
label variable peschlvl "Would that be high school, college, or university?"
label variable prnlfsch "NLF activity - in school or not in school"
label variable pwfmwgt "Family weight"
label variable pwlgwgt "Longitudinal weight"
label variable pworwgt "Outgoing rotation weight"
label variable pwsswgt "Final weight"
label variable pwvetwgt "Veterans weight"
label variable prchld "Presence of own children < 18 years of age by selected age group"
label variable prnmchld "Number of own children < 18 years of age"
label variable pxpdemp1 "Allocation flag"
label variable prwernal "Allocation flag weekly earnings recode (PRERNWA)"
label variable prhernal "Allocation flag hourly earnings recode (PRERNHLY)"
label variable hxtenure "Allocation flag"
label variable hxhousut "Allocation flag"
label variable hxtelhhd "Allocation flag"
label variable hxtelavl "Allocation flag"
label variable hxphoneo "Allocation flag"
label variable pxinusyr "Allocation flag"
label variable pxrrp "Allocation flag"
label variable pxparent "Allocation flag"
label variable pxage "Allocation flag"
label variable pxmaritl "Allocation flag"
label variable pxspouse "Allocation flag"
label variable pxsex "Allocation flag"
label variable pxafwhn1 "Allocation flag"
label variable pxafnow "Allocation flag"
label variable pxeduca "Allocation flag"
label variable pxrace1 "Allocation flag"
label variable pxnatvty "Allocation flag"
label variable pxmntvty "Allocation flag"
label variable pxfntvty "Allocation flag"
label variable pxnmemp1 "Allocation flag"
label variable pxhspnon "Allocation flag"
label variable pxmlr "Allocation flag"
label variable pxret1 "Allocation flag"
label variable pxabsrsn "Allocation flag"
label variable pxabspdo "Allocation flag"
label variable pxmjot "Allocation flag"
label variable pxmjnum "Allocation flag"
label variable pxhrusl1 "Allocation flag"
label variable pxhrusl2 "Allocation flag"
label variable pxhrftpt "Allocation flag"
label variable pxhruslt "Allocation flag"
label variable pxhrwant "Allocation flag"
label variable pxhrrsn1 "Allocation flag"
label variable pxhrrsn2 "Allocation flag"
label variable pxhract1 "Allocation flag"
label variable pxhract2 "Allocation flag"
label variable pxhractt "Allocation flag"
label variable pxhrrsn3 "Allocation flag"
label variable pxhravl "Allocation flag"
label variable pxlayavl "Allocation flag"
label variable pxlaylk "Allocation flag"
label variable pxlaydur "Allocation flag"
label variable pxlayfto "Allocation flag"
label variable pxlkm1 "Allocation flag"
label variable pxlkavl "Allocation flag"
label variable pxlkll1o "Allocation flag"
label variable pxlkll2o "Allocation flag"
label variable pxlklwo "Allocation flag"
label variable pxlkdur "Allocation flag"
label variable pxlkfto "Allocation flag"
label variable pxdwwnto "Allocation flag"
label variable pxdwrsn "Allocation flag"
label variable pxdwlko "Allocation flag"
label variable pxdwwk "Allocation flag"
label variable pxdw4wk "Allocation flag"
label variable pxdwlkwk "Allocation flag"
label variable pxdwavl "Allocation flag"
label variable pxdwavr "Allocation flag"
label variable pxjhwko "Allocation flag"
label variable pxjhrsn "Allocation flag"
label variable pxjhwant "Allocation flag"
label variable pxio1cow "Allocation flag"
label variable pxio1icd "Allocation flag"
label variable pxio1ocd "Allocation flag"
label variable pxio2cow "Allocation flag"
label variable pxio2icd "Allocation flag"
label variable pxio2ocd "Allocation flag"
label variable pxernuot "Allocation flag"
label variable pxernper "Allocation flag"
label variable pxernh1o "Allocation flag"
label variable pxernhro "Allocation flag"
label variable pxern "Allocation flag"
label variable pxpdemp2 "Allocation flag"
label variable pxnmemp2 "Allocation flag"
label variable pxernwkp "Allocation flag"
label variable pxernrt "Allocation flag"
label variable pxernhry "Allocation flag"
label variable pxernh2 "Allocation flag"
label variable pxernlab "Allocation flag"
label variable pxerncov "Allocation flag"
label variable pxnlfjh "Allocation flag"
label variable pxnlfret "Allocation flag"
label variable pxnlfact "Allocation flag"
label variable pxschenr "Allocation flag"
label variable pxschft "Allocation flag"
label variable pxschlvl "Allocation flag"
label variable qstnum "Unique household identifier."
label variable occurnum "Unique person identifier."
label variable pedipged "How did...get...'s high school diploma?"
label variable pehgcomp "What was the highest grade of regular school...completed before receiving...'s GED?"
label variable pecyc "How many years of college credit has...completed?"
label variable pxdipged "Allocation flag"
label variable pxhgcomp "Allocation flag"
label variable pxcyc "Allocation flag"
label variable pwcmpwgt "Composited final weight. Used to create BLS's published labor force statistics"
label variable peio1icd "Industry code for primary job"
label variable peio1ocd "Occupation code for primary job."
label variable peio2icd "Industry code for second job."
label variable peio2ocd "Occupation code for second job."
label variable primind1 "Intermediate industry recode (job 1)"
label variable primind2 "Intermediate industry recode (job 2)"
label variable peafwhn1 "When did you serve?"
label variable peafwhn2 "When did you serve?"
label variable peafwhn3 "When did you serve?"
label variable peafwhn4 "When did you serve?"
label variable pxafever "Allocation flag"
label variable pelndad "Line number of father"
label variable pelnmom "Line number of mother"
label variable pedadtyp "Type of father"
label variable pemomtyp "Type of mother"
label variable pecohab "Line number of cohabiting partner"
label variable pxlndad "Allocation flag"
label variable pxlnmom "Allocation flag"
label variable pxdadtyp "Allocation flag"
label variable pxmomtyp "Allocation flag"
label variable pxcohab "Allocation flag"
label variable pedisear "Is...deaf or does ...have serious difficulty hearing?"
label variable pediseye "Is...blind or does...have serious difficulty seeing even when wearing glasses?"
label variable pedisrem "Because of a physical, mental, or emotional condition, does...have serious difficulty concentrating, remembering, or making decisions?"
label variable pedisphy "Does...have serious difficulty walking or climbing stairs?"
label variable pedisdrs "Does...have difficulty dressing or bathing?"
label variable pedisout "Because of a physical, mental, or emotional condition, does...have difficulty doing errands alone such as visiting a doctor’s office or shopping?"
label variable prdisflg "Does this person have any of these disability conditions?"
label variable pxdisear "Allocation flag"
label variable pxdiseye "Allocation flag"
label variable pxdisrem "Allocation flag"
label variable pxdisphy "Allocation flag"
label variable pxdisdrs "Allocation flag"
label variable pxdisout "Allocation flag"
label variable hxfaminc "Allocation flag"
label variable prdasian "Detailed Asian race recode"
label variable pepdemp1 "Does this person usually have any paid employees?"
label variable ptnmemp1 "Excluding all owners, how many paid employees does this person usually have?"
label variable pepdemp2 "Does this person usually have any paid employees?"
label variable ptnmemp2 "Excluding all owners, how many paid employees does this person usually have?"
label variable penxtpr "Line number of person being interviewed"
label variable penxtpr3 "Is this self or proxy?"
label variable pea1 "(Have/Has) (you/ name) smoked at least 100 cigarettes in (your/his/her) entire life? 100 cigarettes = approximately 5 packs"
label variable pea2 "How old (were/was) (you/name) when (you/he/she) first started smoking cigarettes FAIRLY REGULARLY?"
label variable pea2a "You said that (you/name) never smoked regularly. How old (were/was) (you/name) the first time (you/he/she) smoked part or all of a cigarette?"
label variable pra2b1 "In what state or country did (you/name) live when (you/he/she) started to smoke cigarettes fairly regularly?"
label variable pra2c1 "In what state or country did (you/name) live when (you/he/she) FIRST smoked part or all of a cigarette?"
label variable pea3 "(Do/Does) (you/name) now smoke cigarettes every day, some days, or not at all?"
label variable ptb1 "On the average, about how many cigarettes do you now smoke each day?"
label variable peb1a "Would you say that, on average, you now smoke more or less than 20 cigarettes each day?"
label variable peb2 "Do you usually smoke menthol or non-menthol cigarettes?"
label variable peb5anum "How soon after you wake up do you typically smoke your first cigarette of the day? (number)"
label variable peb5aunt "How soon after you wake up do you typically smoke your first cigarette of the day? (unit)"
label variable peb5b "Would you say you smoke your first cigarette of the day within the first 30 minutes?"
label variable peba6a "Do you usually buy your own cigarettes?"
label variable peb6a "Do you USUALLY buy your cigarettes by the pack or by the carton?"
label variable ptb6b "What price did you pay for the LAST pack of cigarettes you bought? Please report the cost after using discounts or coupons."
label variable ptb6c "What price did you pay for the LAST carton of cigarettes you bought? Please report the cost after using discounts or coupons."
label variable peb6c4 "Did you use coupons, rebates, or any other special promotions when you bought your LAST (B6a fill PACK/CARTON) of cigarettes?"
label variable peb6d1 "Did you buy your LAST (pack/carton) of cigarettes in (fill respondent's state of residence) or in some other state?"
label variable peb6d2 "In what other state did you buy your LAST (pack/carton) of cigarettes?"
label variable peb6d3 "Did you buy you LAST (pack/carton) of cigarettes from an Indian reservation?"
label variable peb6doth "Was the Other Way in which you purchased your LAST (pack/carton) of cigarettes:"
label variable peb6e1 "In the LAST 2 months, have you bought any SINGLE or INDIVIDUAL cigarettes?"
label variable peb6e31 "Did you buy your LAST SINGLE or INDIVIDUAL cigarette in [fill respondent’s state of residence] or in some other state or country?"
label variable prb6e32a "In what OTHER state or country did you buy your LAST SINGLE OR INDIVIDUAL cigarette?"
label variable peb7c "For how long have you smoked EVERY DAY?"
label variable peb7c2 "Have you EVER smoked MENTHOL cigarettes for 6 months or more?"
label variable peb7c3 "For how long (have you smoked/did you smoke) MENTHOL cigarettes?"
label variable peb8 "Around this time 12 MONTHS AGO, were you smoking cigarettes every day, some days, or not at all?"
label variable ptb9 "Around this time 12 months ago, on the average about how many cigarettes did you smoke each day?"
label variable peb10a "Around this time 12 months age, on how many of 30 days in the month did you smoke cigarettes?"
label variable ptb10b "On the average, on those (fill entry B10a) days, how many cigarettes did you usually smoke each day?"
label variable pec1 "On how many of the past 30 days did you smoke cigarettes?"
label variable pec1i "Would you say you smoked on at least 12 days in the past 30 days?"
label variable ptc1a "On the average, on those [fill entry C1] days, how many cigarettes did you usually smoke each day?"
label variable pec2 "Do you usually smoke menthol or non-menthol cigarettes?"
label variable pec5anum "On the days that you smoke, how soon after you wake up do you typically smoke your first cigarette of the day? (number)"
label variable pec5aunt "On the days that you smoke, how soon after you wake up do you typically smoke your first cigarette of the day? (unit)"
label variable pec5b "On the days that you smoke, would you say you smoke your first cigarette of the day within the first 30 minutes?"
label variable peca6a "Do you usually buy your own cigarettes?"
label variable pec6a "Do you USUALLY buy your cigarettes by the pack or by the carton?"
label variable ptc6b "What price did you pay for the LAST pack of cigarettes you bought? Please report the cost after using discounts or coupons."
label variable ptc6c "What price did you pay for the LAST carton of cigarettes you bought? Please report the cost after using discounts or coupons."
label variable pec6c4 "Did you use coupons, rebates, or any other special promotions when you bought your LAST (pack/carton) of cigarettes?"
label variable pec6d1 "Did you buy your LAST (pack/carton) of cigarettes in (fill respondent's state of residence) or in some other state?"
label variable pec6d2 "In what other state did you buy your LAST (pack/carton) of cigarettes?"
label variable pec6d3 "Did you buy your LAST (pack/carton) of cigarettes from an Indian reservation?"
label variable pec6doth "Was the 'Other Way' in which you purchased your Last (pack/carton) of cigarettes."
label variable pec6e1 "In the LAST 2 months, have you bought any SINGLE or INDIVIDUAL cigarettes?"
label variable pec6e31 "Did you buy your LAST SINGLE or INDIVIDUAL cigarette in [fill respondent’s state of residence] or in some other state or other country?"
label variable prc6e32a "In what OTHER state did you buy your LAST SINGLE OR INDIVIDUAL cigarette?"
label variable pec7a "Have you EVER smoked cigarettes EVERY DAY for at least 6 months?"
label variable pec7d "For how long did you smoke EVERY DAY?"
label variable pec7d2 "Have you EVER smoked MENTHOL cigarettes for 6 months or more?"
label variable pec7d3 "For how long (have you smoked/did you smoke) MENTHOL cigarettes?"
label variable ptc7e "When you last smoked every day, on average how many cigarettes did you smoke each day?"
label variable pec8 "Around this time 12 MONTHS AGO, were you smoking cigarettes every day, some days, or not at all?"
label variable ptc9 "Around this time 12 months ago, on the average about how many cigarettes did you smoke each day?"
label variable pec10a "Around this time 12 months age, on how many of 30 days in the month did you smoke cigarettes?"
label variable ptc10b "On the average, on those (fill entry c10a) days, how many cigarettes did you usually smoke each day?"
label variable peda "During the PAST 12 MONTHS, have you TRIED to QUIT smoking COMPLETELY?"
label variable pedb "Have you EVER TRIED to QUIT smoking COMPLETELY?"
label variable ped1r "During the PAST 12 MONTHS, have you stopped smoking for one day or longer BECAUSE YOU WERE TRYING TO QUIT SMOKING?"
label variable ped3 "How many TIMES during the past 12 months have you stopped smoking for one day or longer BECAUSE YOU WERE TRYING TO QUIT SMOKING?"
label variable ped3b "Would you say that during the past 12 months it was MORE THAN 3 TIMES that you have stopped smoking for one day or longer BECAUSE YOU WERE TRYING TO QUIT SMOKING?"
label variable ped6num "During the PAST 12 MONTHS, what is the length of this single quit attempt where you stopped smoking because you were TRYING to quit smoking? (number)"
label variable ped6unt "During the PAST 12 MONTHS, what is the length of this single quit attempt where you stopped smoking because you were TRYING to quit smoking? (unit)"
label variable ped6b "Was it more or less than one week?"
label variable ped6cnum "Thinking of those attempts during the past 12 months, what was the length of time of the ONE attempt that lasted the longest? (number)"
label variable ped6cunt "Thinking of those attempts during the past 12 months, what was the length of time of the ONE attempt that lasted the longest? (unit)"
label variable ped6c2 "Was it more or less than one week?"
label variable ped7r "DURING THE PAST 12 MONTHS, have you made a serious attempt to stop smoking because you were TRYING to quit – even if you stopped for less than a day?"
label variable ped8r "Have you EVER made a serious attempt to stop smoking because you were 'TRYING to quit'; even if you stopped for less than a day?"
label variable pee1b1 "Thinking back to the (last time/time) you tried to QUIT smoking in the past 12 months. Did you use ANY of the following: A telephone help line or quit line?"
label variable pee1b5 "Thinking back to the (last time/time) you tried to QUIT smoking in the past 12 months. Did you use ANY of the following: Internet or web based program or tool?"
label variable pee1c2 "The (last time/time) you tried to QUIT smoking in the past 12 months: Did you do ANY of the following: Try to quit by SWITCHING to smokeless tobacco such as chewing tobacco, snuff, or snus?"
label variable pee1c2b "The (last time/time) you tried to QUIT smoking in the past 12 months. Did you do ANY of the following: Try to quit by SWITCHING to regular cigars, cigarillos, little filtered cigars or any pipes filled with tobacco?"
label variable pee1c2c "The (last time/time) you tried to QUIT smoking in the past 12 months. Did you do ANY of the following: Try to quit by SWITCHING to electronic or E-cigarettes?"
label variable pee1c2d1 "Did you switch to? Cigars, cigarillos, little filtered cigars."
label variable pee1c2d2 "Did you switch to? Regular pipes filled with tobacco."
label variable pee1c2d3 "Did you switch to? Water or hookah (pronounced who-kah) pipes filled with tobacco."
label variable pee1cz2c "The (LAST TIME/TIME) you tried to quit smoking in the past 12 months, did you try to quit by SWITCHING to electronic or E-Cigarettes? You may also know them as vape-pens, hookah-pens, E-hookahs, E-vaporizers, E-Cigars, or E-Pipes."
label variable pef1a "In the PAST 12 MONTHS, have you seen a medical doctor?"
label variable pef1b "During the PAST 12 MONTHS, did any medical doctor ADVISE you to stop smoking?"
label variable peg1 "Are you seriously considering quitting smoking within the next 6 months?"
label variable peg2 "Are you planning to quit within the next 30 days?"
label variable peg3 "Overall, on a scale from 1 to 10 where 1 is NOT AT ALL interested and 10 is EXTREMELY interested, how interested are you in quitting smoking?"
label variable peg4 "If you did try to quit smoking altogether in the next 6 months, how LIKELY do you think you would be to succeed --not at all, a little likely, somewhat likely or very likely?"
label variable peh1num "About how long has it been since you COMPLETELY quit smoking cigarettes? (number)"
label variable peh1unt "About how long has it been since you COMPLETELY quit smoking cigarettes? (unit)"
label variable peh1b "In the PAST 12 months, was H1 the longest time you stopped smoking cigarettes because you were trying to quit?"
label variable peh1cnum "During the PAST 12 MONTHS, what WAS the LONGEST length of time you stopped smoking because you were TRYING to quit smoking... (number)"
label variable peh1cunt "During the PAST 12 MONTHS, what WAS the LONGEST length of time you stopped smoking because you were TRYING to quit smoking... (unit)"
label variable peh2 "Have you EVER smoked cigarettes EVERY DAY for at least 6 months?"
label variable peh5 "For how long did you smoke EVERY DAY?"
label variable pth5a "When you last smoked every day, on average how many cigarettes did you smoke each day?"
label variable peh6 "Around this time 12 MONTHS AGO, were you smoking cigarettes every day, some days, or not at all?"
label variable pth6a "Around this time 12 MONTHS AGO, on the average, about how many cigarettes did you smoke each day?"
label variable peh6b "Around this time 12 MONTHS AGO, on how many of 30 days in the month did you smoke cigarettes?"
label variable pth6c "On the average, on those (Fill PEH6b entry), how many cigarettes did you usually smoke each day?"
label variable peh6c2 "We are still talking about Around this time 12 months ago. Thinking back to the 12 MONTHS BEFORE YOUQUIT SMOKING CIGARETTES, during that time, did you usually smoke menthol or non-menthol cigarettes?"
label variable peh6c4 "Have you EVER smoked MENTHOL cigarettes for 6 months or more?"
label variable peh6c5 "For how long have you smoked MENTHOL cigarettes?"
label variable peh6e1 "Now I would like to ask you about HOW you went about completely quitting smoking.  When you quit smoking completely, did you use ANY of the following: A telephone help line or quit line?"
label variable peh6e5 "When you quit smoking completely, did you use ANY of the following: The Internet or a web-based program or tool?"
label variable peh6fa2 "When you quit smoking completely, did you do ANY of the following, whether or not you think they were effective: Try to quit by SWITCHING to smokeless tobacco such as chewing tobacco, snuff, or snus?"
label variable peh6fa2b "When you quit smoking completely, did you do ANY of the following, whether or not you think they were effective: Try to quit by SWITCHING to regular cigars, cigarillos, little filtered cigars or ANY pipes filled with tobacco?"
label variable peh6fa2c "When you quit smoking completely, did you do ANY of the following, whether or not you think they were effective: Try to quit by SWITCHING to electronic or E-Cigarettes?"
label variable peh6fa2d1 "Did you switch to? Cigars, cigarillos, little filtered cigars."
label variable peh6fa2d2 "Did you switch to? Regular pipes filled with tobacco."
label variable peh6fa2d3 "Did you switch to? Water or hookah pipes filled with tobacco."
label variable peh6faz2c "When you quit smoking completely, did you try to quit by SWITCHING to electronic or E-cigarettes?"
label variable peh61a "In the 12 MONTHS BEFORE you COMPLETELY quit smoking, did you SEE a medical doctor?"
label variable peh61b "During the 12 MONTHS BEFORE you completely quit smoking, did any medical doctor ADVISE you to stop smoking?"
label variable peh8anum "During the 12 MONTHS before you quit smoking, how soon after you woke up did you typically smoke your first cigarette of the day? (number)"
label variable peh8aunt "During the 12 MONTHS before you quit smoking, how soon after you woke up did you typically smoke your first cigarette of the day? (unit)"
label variable peh8b "During the 12 months before you quit smoking, would you say you smoked your first cigarette of the day within the first 30 minutes of awakening?"
label variable peh11a "Thinking back to the 12 MONTHS BEFORE YOU COMPLETELY QUIT SMOKING CIGARETTES. During that time, DID YOU USUALLY SMOKE menthol or non-menthol cigarettes?"
label variable peh11c "Have you EVER smoked MENTHOL cigarettes for 6 months or more?"
label variable peh11d "For how long had you smoked MENTHOL cigarettes?"
label variable pej1a1 "(Have/Has) (you/name) EVER used any of the following EVEN ONE TIME? ... A regular cigar or cigarillo OR a little filtered cigar?"
label variable pej1a2 "(Have/Has) (you/name) EVER used any of the following EVEN ONE TIME? ... A regular pipe filled with tobacco?"
label variable pej1a3 "(Have/Has) (you/name) EVER used any of the following EVEN ONE TIME? ... a water pipe or hookah (who-kah) pipe filled with tobacco?"
label variable pej1a3_5 "(Have/Has) (you/name) EVER used E-cigarettes EVEN ONE TIME?"
label variable pej1a4 "(Have/Has) (you/name) EVER used any of the following EVEN ONE TIME? ... Smokeless tobacco, such as moist snuff, dip, spit, chew tobacco or snus?"
label variable pej1a5 "(Have/Has) (you/name) EVER used disolvable tobacco EVEN ONE TIME?"
label variable pej2a1 "(Do you/Does name) NOW smoke regular cigars or cigarillos or little filtered cigars every day, some days or not at all?"
label variable pej2b1 "On how many of the past 30 days did you smoke regular cigars or cigarillos or little filtered cigars?"
label variable pej2a2 "(Do you/Does name) NOW smoke a regular pipe every day, some days or not at all?"
label variable pej2b2 "On how many of the past 30 days did you smoke a regular pipe?"
label variable pej2a3 "(Do you/Does name) NOW use a water pipe or hookah pipe filled with tobacco every day, some days or not at all?"
label variable pej2b3 "On how many of the past 30 days did you use a water pipe or hookah pipe filled with tobacco?"
label variable pej2a3_5 "(Do you /Does name) NOW use an E-cigarette every day, some days or not at all?"
label variable pej2b3_5 "On how many of the past 30 days did you use an E-cigarette?"
label variable pej2a4 "(Do you /Does name) NOW use smokeless tobacco such as moist snuff, dip, spit, chew tobacco or snus every day, some days or not at all?"
label variable pej2b4 "On how many of the past 30 days did you use smokeless tobacco?"
label variable pej2a5 "(Do you /Does name) NOW use dissolvable tobacco every day, some days or not at all?"
label variable pej2b5 "On how many of the past 30 days did you use dissolvable tobacco?"
label variable peja "During the past 30 days, what BRAND of smokeless tobacco (If necessary: moist snuff, dip, spit, chew or snus) did you use MOST OFTEN?"
label variable pejb "During the PAST 30 days, what type of CIGAR did you use MOST OFTEN?"
label variable pejc "During the PAST 30 days, what BRAND of CIGAR did you smoke MOST OFTEN?"
label variable pejnflvin "Some tobacco products come in flavors such as menthol or mint, clove, spice, fruit, chocolate, alcohol,or other flavors."
label variable pejnflvr1 "Some tobacco products come in flavors such as menthol or mint, clove, spice, fruit, chocolate, alcohol, or other flavors.  When you smoke a cigar is it usually flavored?"
label variable pejnflvr2 "Some tobacco products come in flavors such as menthol or mint, clove, spice, fruit, chocolate, alcohol, or other flavors.  When you smoke a regular pipe filled with tobacco is it usually flavored?"
label variable pejnflvr3 "Some tobacco products come in flavors such as menthol or mint, clove, spice, fruit, chocolate, alcohol, or other flavors.  When you smoke a water/hookah pipe filled with tobacco is it usually flavored?"
label variable pejnflv35 "Some tobacco products come in flavors such as menthol or mint, clove, spice, fruit, chocolate, alcohol, or other flavors.  When you use an E-cigarette is it usually flavored?"
label variable pejnflvr4 "Some tobacco products come in flavors such as menthol or mint, clove, spice, fruit, chocolate, alcohol, or other flavors.  When you use smokeless tobacco is it usually flavored?"
label variable pejnflvr5 "Some tobacco products come in flavors such as menthol or mint, clove, spice, fruit, chocolate, alcohol, or other flavors.  When you use dissolvable tobacco is it usually flavored?"
label variable pejecigra " The next questions are about the reasons people use E-cigarettes. Please select which reasons apply to you.  I can use E-cigarettes at times when or in places where smoking cigarettes isn't allowed."
label variable pejecigrb " The next questions are about the reasons people use E-cigarettes. Please select which reasons apply to you.  They might be less harmful to me than cigarettes."
label variable pejecigrc " The next questions are about the reasons people use E-cigarettes. Please select which reasons apply to you.  They might be less harmful to people around me than cigarettes."
label variable pejecigrd " The next questions are about the reasons people use E-cigarettes. Please select which reasons apply to you.  Using E-cigarettes helps people to quit smoking cigarettes."
label variable pejd11 "About how long has it been since you COMPLETELY quit smoking cigars, cigarillos or little filter cigars? (number)"
label variable pejd21 "About how long has it been since you COMPLETELY quit smoking cigars, cigarillos or little filter cigars? (unit)"
label variable pejd12 "About how long has it been since you COMPLETELY quit smoking a regular pipe filled with tobacco? (number)"
label variable pejd22 "About how long has it been since you COMPLETELY quit smoking a regular pipe filled with tobacco? (unit)"
label variable pejd13 "About how long has it been since you COMPLETELY quit smoking a water pipe or hookah pipe filled with tobacco? (number)"
label variable pejd23 "About how long has it been since you COMPLETELY quit smoking a water pipe or hookah pipe filled with tobacco? (unit)"
label variable pejd13_5 "About how long has it been since you COMPLETELY quit using E-cigarettes? (number)"
label variable pejd23_5 "About how long has it been since you COMPLETELY quit using E-cigarettes? (unit)"
label variable pejd14 "About how long has it been since you COMPLETELY quit using a smokeless tobacco? (number)"
label variable pejd24 "About how long has it been since you COMPLETELY quit using a smokeless tobacco? (unit)"
label variable pejd15 "About how long has it been since you COMPLETELY quit using a dissolvable tobacco? (number)"
label variable pejd25 "About how long has it been since you COMPLETELY quit using a dissolvable tobacco? (unit)"
label variable pejd31 "In total, how many years (have you smoked/did you smoke) cigars or cigarillos or little filtered cigars?"
label variable pejd32 "In total, how many years (have you smoked/did you smoke) a regular pipe filled with tobacco?"
label variable pejd33 "In total, how many years (have you smoked/did you smoke) a water pipe or hookah pipe filled with tobacco?"
label variable pejd33_5 "In total, how many years (have you used/did you use) an E-cigarette?"
label variable pejd34 "In total, how many years (have you used/did you use) smokeless tobacco?"
label variable pejd35 "In total, how many years (have you used/did you use) dissolvable tobacco?"
label variable pejfecgra "The next questions are about the reasons people use E-cigarettes. Please select which reasons applied to you when you used to use E-cigarettes.  I could use E-cigarettes at times when or in places where smoking cigarettes wasn't allowed."
label variable pejfecgrb "The next questions are about the reasons people use E-cigarettes. Please select which reasons applied to you when you used to use E-cigarettes.  They might have been less harmful to me than cigarettes."
label variable pejfecgrc "The next questions are about the reasons people use E-cigarettes. Please select which reasons applied to you when you used to use E-cigarettes.  They might be less harmful to people around me than cigarettes."
label variable pejfecgrd "The next questions are about the reasons people use E-cigarettes. Please select which reasons applied to you when you used to use E-cigarettes.  Using E-cigarettes helps people to quit smoking cigarettes."
label variable pej3a1 "How soon after you wake up do you typically (fill text from PRJ3A1F recode)? (number)"
label variable pej3a2 "How soon after you wake up do you typically (fill text from PRJ3A1F recode)? (unit)"
label variable pej3d "Would you say you first (fill text from PRJ3DF recode) within the first 30 minutes of awakening?"
label variable pej3f1 "In the 12 months BEFORE YOU COMPLETELY QUIT (Fill text from PRJ3F1F recode), how soon after you woke up did you typically (Fill text from PRJ3F1F recode)? (number)"
label variable pej3f2 "In the 12 months BEFORE YOU COMPLETELY QUIT (Fill text from PRJ3F1F recode), how soon after you woke up did you typically (Fill text from PRJ3F1F recode)? (unit)"
label variable pej3g "Would you say you first used (Fill text from PRJ3GF recode) within the first 30 minutes of awakening?"
label variable pej4 "During the PAST 12 MONTHS, have you stopped (Fill text from PRJ4F recode) for one day or longer BECAUSE YOU WERE TRYING TO QUIT?"
label variable pej6bnum "Thinking of ANY attempts to stop (fill text from PRJ6BNMF) because you were trying to quit, during the past 12 MONTHS, what is the LONGEST length of time of the ONE attempt that lasted the longest? (number)"
label variable pej6bunt "Thinking of ANY attempts to stop (fill text from PRJ6BNMF) because you were trying to quit, during the past 12 MONTHS, what is the LONGEST length of time of the ONE attempt that lasted the longest? (unit)"
label variable pej7b1 "(Thinking back about the last time you tried to quit (fill text from PRJ7B1F) in the past 12 months/Now I would like to ask about... When you COMPLETELY quit (fill text from PRJ7B1F), did you use: A telephone help line or quit line?"
label variable pej7b5 "(Thinking back about the last time you tried to quit (fill text from PRJ7B1F) in the past 12 months/Now I would like to ask about... When you COMPLETELY quit, did you use: The internet or a web-based program?"
label variable pek1a "Do you mainly work indoors or outdoors?"
label variable pek1b "Do you mainly work in an office building, your own home, in someone else's home, or in another indoor place?"
label variable pek1b11 "In which State (including DC), do you work?"
label variable pek1b2 "When you work INDOORS: Do you mainly work in an office building, in your own home, in someone else's home, or in another indoor place?"
label variable pek1c1 "In which State (including DC), do you work on your main indoor job or business?"
label variable pek2a "Is smoking restricted in ANY WAY at your place of work?"
label variable pek3a "Which of these best describes the smoking policy at your place of work for INDOOR PUBLIC OR COMMON AREAS, such as lobbies, rest rooms, and lunch rooms?"
label variable pek3b "Which of these best describes the smoking policy at your place of work for INDOOR WORK AREAS?"
label variable pek3d "Within the PAST 12 MONTHS, has your employer offered any stop smoking program or any other help to employees who want to quit smoking?"
label variable pek4 "Which statement best describes the rules about smoking INSIDE YOUR HOME?"
label variable pek5a "In buildings with MULTIPLE apartments or living areas, do you THINK that smoking should be ... ALLOWED INSIDE ALL apartments or living areas, ALLOWED inside SOME apartments ..., or NOT ALLOWED at ALL inside apartments?"
label variable pek5b "Now think about INDOOR PUBLIC OR COMMON areas in buildings with MULTIPLE apartments, such as ... Do you THINK that smoking should be ... ALLOWED in ALL such INSIDE COMMON areas, allowed in SOME INSIDE COMMON areas, or NOT allowed at ALL..?"
label variable pek6b "In indoor work areas, do you THINK that smoking SHOULD be allowed in ALL areas, allowed in SOME areas, or NOT allowed at ALL?"
label variable pek6c "Inside bars, cocktail lounges, and clubs, do you THINK that smoking SHOULD be allowed in ALL areas, allowed in SOME areas, or NOT allowed at ALL?"
label variable pek6g "Inside casinos, do you THINK that smoking SHOULD be allowed in ALL areas, allowed in SOME areas, or NOT allowed at ALL?"
label variable pek6ga "On outdoor children's playgrounds and outdoor children's sports fields, do you THINK that smoking SHOULD be allowed in ALL areas, allowed in SOME areas, or NOT allowed at ALL?"
label variable pek6h "Inside a car, when there are other people present, do you THINK that smoking SHOULD..."
label variable pek6h2 "IF children are present inside the car, do you think that smoking SHOULD..."
label variable pes78 "Respondent relationship recode - relationship of respondent to the sample person"
label variable pesinttp "In what language was the interview conducted for this person?"
label variable pes81a "Method of Interview"
label variable intrview "Interview Status Recode"
label variable hrmode "Method of Interview"
label variable smokstat "Type of smoker recode"
label variable prs35 "Respondent and Smoker Type"
label variable prs60 "Self responding 'Not at all' smokers- smoking less than or equal to 1 year or don't know"
label variable prs64 "Who is responding for the supplement"
label variable prs65 "Monthly Labor Force recode of Self respondents"
label variable prs66 "Employed self respondents' class of worker on first job"
label variable prj3a1f "Recode from fill in PEJ3a1 and PEJ3a2 to determine which tobacco product is being discussed in PEJ3a1 and PEJ3a2"
label variable prj3df "Recode from fill in PEJ3d to determine which tobacco product is being discussed in PEJ3d"
label variable prj3f1f "Recode from fill in PEJ3f1 and PEJ3f2 to determine which tobacco product is being discussed in PEJ3f1 and PEJ3f2"
label variable prj3gf "Recode from fill in PEJ3g to determine which tobacco product is being discussed in PEJ3g"
label variable prj4f "Recode from fill in PEJ4 to determine which tobacco product is being discussed in PEJ4"
label variable prj6bnmf "Recode from fill in PEJ6bnum and PEJ6bunt to see which tobacco product is being discussed in PEJ6bnum and PEJ6bunt"
label variable prj7b1f "Recode identifying which tobacco product the respondent has quit or has tried to quit in PEJ7b1, PEJ7b5"
label variable prsiflg "Recode identifies person answering their own questions on the shorter proxy path."
label variable pwnrwgt "Nonresponse weight"
label variable pwsrwgt "Self response weight"